# Configuration for the Wind ML pipeline
# ======================================

data:
  raw_path: "data/raw/wind_data.csv"

# Data generation (development phase)
data_generation:
  start_date: "2025-08-12"
  num_days: 60
  noise_level: 0.1
  seed: 42
  output_path: "data/raw/wind_data.csv"

# Data preparation
data_preprocessing:
  input_path: "data/processed/aligned.csv"
  output_dir: "data/processed"
  test_size: 0.2
  random_state: 42
  temporal_split: true
  target_mode: "delta"
  artifacts_dir: "artifacts"
  feature_engineering:
    temporal_features: true
    lag_features: true
    rolling_features: true
    rolling_window: 3

# Model training
model_training:
  experiment_name: "wind_prediction"
  models:
    linear_regression: {}
    ridge_regression:
      alpha: 1.0
    random_forest:
      n_estimators: 100
      random_state: 42
      n_jobs: -1
  metrics:
    - rmse
    - mae
    - r2
  results_path: "results/model_comparison.yaml"

# MLflow configuration
mlflow:
  tracking_uri: "file:./mlruns"
  experiment_name: "wind_prediction"

# Weather API settings
weather:
  provider: "openmeteo"
  openmeteo:
    lat: 49.223
    lon: 18.739
    hours: 48
    output_path: "data/raw/forecast_openmeteo.csv"

# Data alignment between forecast and measurements
alignment:
  forecast_path: "data/raw/forecast_openmeteo.csv"
  measurements_path: "data/raw/wind_data.csv"
  output_path: "data/processed/aligned.csv"
  tolerance_minutes: 30
  resample_rule: null
